Repository exercism/emacs-lisp, pull requests merged in 2024-07, with the labels that each got.

#430 Sync protein-translation tests
  exercises/practice/protein-translation/.meta/tests.toml
  exercises/practice/protein-translation/protein-translation-test.el
Labels: x:action/sync, x:rep/tiny

#429 Sync exercise docs
  exercises/practice/affine-cipher/.docs/instructions.md
  exercises/practice/pascals-triangle/.docs/instructions.md
  exercises/practice/pascals-triangle/.docs/introduction.md
  exercises/practice/zebra-puzzle/.docs/instructions.md
  exercises/practice/zebra-puzzle/.docs/introduction.md
  exercises/practice/zebra-puzzle/.meta/example.el
Labels: x:action/sync, x:rep/tiny

#422 Parallel letter frequency
  config.json
  exercises/practice/parallel-letter-frequency/.docs/instructions.append.md
  exercises/practice/parallel-letter-frequency/.docs/instructions.md
  exercises/practice/parallel-letter-frequency/.meta/config.json
  exercises/practice/parallel-letter-frequency/.meta/example.el
  exercises/practice/parallel-letter-frequency/.meta/tests.toml
  exercises/practice/parallel-letter-frequency/parallel-letter-frequency-test.el
  exercises/practice/parallel-letter-frequency/parallel-letter-frequency.el
Labels: x:module/practice-exercise, x:rep/massive

#427 add variable-length-quantity exercise
  config.json
  exercises/practice/variable-length-quantity/.docs/instructions.md
  exercises/practice/variable-length-quantity/.meta/config.json
  exercises/practice/variable-length-quantity/.meta/example.el
  exercises/practice/variable-length-quantity/.meta/tests.toml
  exercises/practice/variable-length-quantity/variable-length-quantity-test.el
  exercises/practice/variable-length-quantity/variable-length-quantity.el
Labels: x:module/practice-exercise, x:rep/large

#432 add linked list exercise
  config.json
  exercises/practice/linked-list/.docs/instructions.md
  exercises/practice/linked-list/.docs/introduction.md
  exercises/practice/linked-list/.meta/config.json
  exercises/practice/linked-list/.meta/example.el
  exercises/practice/linked-list/.meta/tests.toml
  exercises/practice/linked-list/linked-list-test.el
  exercises/practice/linked-list/linked-list.el
Labels: x:module/practice-exercise, x:rep/large

#434 add resistor-color-trio exercise
  config.json
  exercises/practice/resistor-color-trio/.docs/instructions.md
  exercises/practice/resistor-color-trio/.meta/config.json
  exercises/practice/resistor-color-trio/.meta/example.el
  exercises/practice/resistor-color-trio/.meta/tests.toml
  exercises/practice/resistor-color-trio/resistor-color-trio-test.el
  exercises/practice/resistor-color-trio/resistor-color-trio.el
Labels: x:module/practice-exercise, x:rep/large

#438 resistor-color-trio: sync
  exercises/practice/resistor-color-trio/.docs/instructions.md
Labels: x:size/tiny

#436 resistor-color: sync
  exercises/practice/resistor-color/.docs/instructions.md
Labels: x:size/tiny

#437 resistor-color-duo: sync
  exercises/practice/resistor-color-duo/.docs/instructions.md
Labels: x:size/tiny
