Repository exercism/emacs-lisp, pull requests merged in 2024-04, with the labels that each got.

#345 all-your-base: sync
  exercises/practice/all-your-base/.docs/instructions.md
  exercises/practice/all-your-base/.docs/introduction.md
Labels: x:size/tiny

#316 Add tests.toml for Queen Attack exercise (closes #313)
  exercises/practice/queen-attack/.meta/tests.toml
Labels: x:action/sync, x:module/practice-exercise, x:rep/tiny

#349 Update example.el relative path
  config.json
Labels: x:action/fix, x:rep/tiny

#358 Sync pangram tests
  exercises/practice/pangram/pangram-test.el
  exercises/practice/pangram/pangram.el
Labels: x:action/sync, x:rep/tiny

#357 Sync nucleotide-count tests
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/nucleotide-count/nucleotide-count.el
Labels: x:action/sync, x:rep/tiny

#356 Sync roman-numerals tests
  exercises/practice/roman-numerals/.meta/config.json
  exercises/practice/roman-numerals/.meta/tests.toml
  exercises/practice/roman-numerals/roman-numerals-test.el
  exercises/practice/roman-numerals/roman-numerals.el
Labels: x:action/sync, x:rep/tiny

#353 Sync armstrong-number tests
  exercises/practice/armstrong-numbers/armstrong-numbers-test.el
  exercises/practice/armstrong-numbers/armstrong-numbers.el
Labels: x:action/sync, x:rep/tiny

#354 Sync raindrops tests
  exercises/practice/raindrops/raindrops-test.el
  exercises/practice/raindrops/raindrops.el
Labels: x:action/sync, x:rep/tiny

#347 Update generator to use configlet create
  bin/generate_practice_exercise
Labels: x:module/practice-exercise, x:rep/tiny

#352 Sync anagram tests
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/anagram-test.el
  exercises/practice/anagram/anagram.el
Labels: x:action/sync, x:rep/tiny

#351 Sync allergies tests
  exercises/practice/allergies/allergies-test.el
  exercises/practice/allergies/allergies.el
Labels: x:action/sync, x:rep/tiny

#350 Sync acronym tests
  exercises/practice/acronym/.meta/example.el
  exercises/practice/acronym/acronym-test.el
  exercises/practice/acronym/acronym.el
Labels: x:action/sync, x:rep/tiny

#348 Add resistor-color-duo exercise
  config.json
  exercises/practice/resistor-color-duo/.docs/instructions.md
  exercises/practice/resistor-color-duo/.meta/config.json
  exercises/practice/resistor-color-duo/.meta/example.el
  exercises/practice/resistor-color-duo/.meta/tests.toml
  exercises/practice/resistor-color-duo/resistor-color-duo-test.el
  exercises/practice/resistor-color-duo/resistor-color-duo.el
Labels: x:module/practice-exercise, x:rep/large

#355 Update difficulty levels to sort exercises
  config.json
Labels: x:module/practice-exercise, x:rep/small

#360 Add missing authors to exercise configs
  exercises/practice/etl/.meta/config.json
  exercises/practice/perfect-numbers/.meta/config.json
  exercises/practice/phone-number/.meta/config.json
  exercises/practice/run-length-encoding/.meta/config.json
  exercises/practice/word-count/.meta/config.json
Labels: x:rep/tiny

#362 Add eliud's eggs
  config.json
  exercises/practice/eliuds-eggs/.docs/instructions.md
  exercises/practice/eliuds-eggs/.docs/introduction.md
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/.meta/example.el
  exercises/practice/eliuds-eggs/.meta/tests.toml
  exercises/practice/eliuds-eggs/eliuds-eggs-test.el
  exercises/practice/eliuds-eggs/eliuds-eggs.el
Labels: x:module/practice-exercise, x:rep/large

#363 Add resistor-color
  config.json
  exercises/practice/resistor-color/.docs/instructions.md
  exercises/practice/resistor-color/.meta/config.json
  exercises/practice/resistor-color/.meta/example.el
  exercises/practice/resistor-color/.meta/tests.toml
  exercises/practice/resistor-color/resistor-color-test.el
  exercises/practice/resistor-color/resistor-color.el
Labels: x:module/practice-exercise, x:rep/large
